import { IGood } from '../types/good.interface';

export const goods: IGood[] = [
	{
		id: 1,
		shopId: 1,
		name: 'Big Mac',
		price: 1.29,
		img: 'img/shops/mcdonlads/Bigmac.png',
	},
	{
		id: 2,
		shopId: 1,
		name: 'Hamburger',
		price: 1.09,
		img: 'img/shops/mcdonlads/Hamburger.png',
	},
	{
		id: 3,
		shopId: 1,
		name: 'Cheeseburger',
		price: 1.59,
		img: 'img/shops/mcdonlads/Cheeseburger.png',
	},
	{
		id: 4,
		shopId: 1,
		name: 'Quarter Pounder®* with Cheese',
		price: 1.44,
		img: 'img/shops/mcdonlads/QuarterPounderwithCheese.png',
	},
	{
		id: 5,
		shopId: 1,
		name: 'Double Quarter Pounder®* with Cheese',
		price: 1.85,
		img: 'img/shops/mcdonlads/DoubleQuarterPounderwithCheese.png',
	},
	{
		id: 6,
		shopId: 1,
		name: 'Quarter Pounder®* with Cheese Deluxe',
		price: 1.99,
		img: 'img/shops/mcdonlads/QuarterPounderCheeseDeluxe.png',
	},
	{
		id: 7,
		shopId: 1,
		name: 'McDouble®',
		price: 1.39,
		img: 'img/shops/mcdonlads/McDouble.png',
	},
	{
		id: 8,
		shopId: 1,
		name: 'Quarter Pounder®* with Cheese Bacon',
		price: 1.79,
		img: 'img/shops/mcdonlads/QuarterPounderCheeseBacon.png',
	},
	{
		id: 9,
		shopId: 1,
		name: 'Double Cheeseburger',
		price: 1.89,
		img: 'img/shops/mcdonlads/DoubleCheeseburger.png',
	},
	{
		id: 10,
		shopId: 2,
		name: 'Bucket Duo Sharp',
		price: 1.39,
		img: 'img/shops/kfc/BucketDuoSharp.png',
	},
	{
		id: 11,
		shopId: 2,
		name: 'Twister Junior Special',
		price: 1.19,
		img: 'img/shops/kfc/TwisterJuniorSpecial.png',
	},
	{
		id: 12,
		shopId: 3,
		name: 'Oleato™ Iced Shaken',
		price: 1.99,
		img: 'img/shops/starbucks/OleatoIcedShaken.png',
	},
	{
		id: 13,
		shopId: 3,
		name: 'Oleato™ Caffé Latte',
		price: 1.75,
		img: 'img/shops/starbucks/OleatoCaffeLatte.png',
	},
];
